# Generated by Django 5.2.7 on 2026-02-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='json_upload',
            field=models.FileField(blank=True, help_text='Toplu kelime eklemek için JSON dosyası yükleyin', null=True, upload_to='word_imports/'),
        ),
        migrations.AlterField(
            model_name='word',
            name='english_word',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='word',
            name='example_sentence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='level',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2),
        ),
        migrations.AlterField(
            model_name='word',
            name='turkish_word',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
